# Header
menu:
  归档: /archives
rss: /atom.xml
title: 橘子太空

author:  橘子
aboutme: 去到此空间。

# Content
excerpt_link: 全文...
fancybox: true
date_format: 'YYYY年MM月DD日'

socials:
  email: "打算加上标签、评论和关于的功能，就算做不来也没关系，能幻想一下已经很厉害了。"
  wechat: "想在实现这些功能以后交写博客的好朋友，等等我吧！不过一般来说应该怎么交往？隔空喊话，还是“我知道你的存在”就行了？笑"
#  github: "https://github.com/gary-Shen"
#  flickr: "https://www.flickr.com/photos/69944455@N05/"
#  email: "guanlinshen@126.com"
#  wechat: "Grinson"

# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

#主题方案
highlight_theme: atom light

# widget behavior
archive_type: 'monthly'
show_count: false

disqus_shortname:

# Miscellaneous
google_analytics: 'UA-61220413-1'
gauges_analytics:
favicon: /images/favicon.ico
avatar: "/images/favicon.ico"
twitter:
google_plus:
fb_admins:
fb_app_id:
